trigger: none

pool: 
  name: Azure Pipelines
  vmImage: ubuntu-latest

stages:
  - stage: deploy
    displayName: Build and Deploy
    variables:
      - group: global-acr
      - group: filesearch-rag
      - name: imageName
        value: 'filesearch-rag-ui-img'
      - name: webApiAppName
        value: 'filesearch-rag-rest-webapi'
    jobs:
      - job: build
        displayName: Build and Publish
        steps:
          - checkout: self            
          - task: Docker@2
            displayName: Build the UI Docker image
            inputs:
              command: 'build'
              containerRegistry: filesearch-rag-docker-servicecon
              repository: '$(imageName)'
              dockerfile: src/FileSearchRAG.Web.UI/Dockerfile
              buildContext: src/FileSearchRAG.Web.UI
              tags: $(Build.BuildId)
              arguments: '--build-arg REACT_APP_API_BASE_URL=https://$(webApiAppName).azurewebsites.net'

          - task: Docker@2
            displayName: Push the Docker image to ACR
            inputs:
              command: 'push'
              containerRegistry: filesearch-rag-docker-servicecon
              repository: '$(imageName)'
              tags: $(Build.BuildId)

          - task: DotNetCoreCLI@2
            displayName: 'Publish Api web app'
            inputs:
              command: 'publish'
              projects: src/FileSearchRAG.Web.API/FileSearchRAG.Web.API.csproj
              arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/FileSearchRAGWebApi'
              publishWebProjects: false
          
          - task: PublishBuildArtifacts@1
            displayName: 'Publish build artifact'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/FileSearchRAGWebApi'
              artifactName: 'FileSearchRAGWebApi'
              deployment_method: zipDeploy
          
      - job: tf_job
        displayName: Run Terraform
        dependsOn: build
        steps:
          - checkout: self            
          - task: TerraformInstaller@0
            displayName: Install Terraform
            inputs:
              terraformVersion: 1.10.5

          - task: TerraformTaskV4@4
            displayName: Terraform init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(Build.SourcesDirectory)/iac'
              backendServiceArm: 'filesearch-rag-servicecon'
              backendAzureRmResourceGroupName: 'tf-filesearch-rag'
              backendAzureRmStorageAccountName: 'filesearchragtfsto'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'terraform.tfstate'

          - task: TerraformTaskV4@4
            displayName: 'Validate Terraform'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(Build.SourcesDirectory)/iac'

          - task: TerraformTaskV4@4
            displayName: Terraform plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              commandOptions: '-out main.tfplan -detailed-exitcode -var "acrpassword=$(acr_password)" -var "image=$(imageName):$(Build.BuildId)" -var "webApiAppName=$(webApiAppName)" -var "pineconeApiKey=$(pineconeApiKey)" -var "openAiApiKey=$(openAiApiKey)"'
              environmentServiceNameAzureRM: 'filesearch-rag-servicecon'
              workingDirectory: '$(Build.SourcesDirectory)/iac'

          - task: TerraformTaskV4@4
            displayName: Terraform apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              commandOptions: 'main.tfplan'
              environmentServiceNameAzureRM: 'filesearch-rag-servicecon'
              workingDirectory: '$(Build.SourcesDirectory)/iac'

      - job: deploy_web_apps_job
        displayName: Deploy Web Api
        dependsOn: tf_job
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Api Artifact'
            inputs:
              artifact: 'FileSearchRAGWebApi'
              path: '$(Build.ArtifactStagingDirectory)/FileSearchRAGWebApi'

          - task: AzureWebApp@1
            displayName: 'Deploy Api Web app'
            inputs:
              azureSubscription: filesearch-rag-servicecon
              appType: webAppLinux
              appName: '$(webApiAppName)'
              package: '$(Build.ArtifactStagingDirectory)/FileSearchRAGWebApi/*.zip'
              deploymentMethod: zipDeploy
            